gnb_id: 0 # Optional UINT (411). Sets the numerical ID associated with the gNB.
gnb_id_bit_length: 32 # Optional UNIT. Sets the bit length of the gnb_id above. Format: integer between [22 - 32]
ran_node_name: srsgnb01 # Optional TEXT (srsgnb01). Sets the text ID associated with the gNB. Format: string without spaces.
gnb_du_id: 0 # Optional UINT (0). Sets the gNB DU ID. Supported: [0 - 68719476735].

slicing: # Optional TEXT. Configure network slicing options. This can only be set via the configuration file.
  - # Configure Slice 1
    sst: 1 # Optional UINT (1). Sets the Slice Service Type. Supported: [0 - 255].
    sd: 1 # Optional UINT (0). Sets the Service Differentiator. Supported: [0-16777215].

amf:
  addr: 192.168.122.100 # Required TEXT. Sets the IP address or hostname of the AMF. Format: IPV4 or IPV6 IP address.
  port: 38412 # Optional UINT (38412). Sets the AMF port. Format: integer between [20000 - 40000].
  bind_addr: 192.168.100.44 # Required TEXT. Sets the local IP address that the gNB binds to for receiving traffic from the AMF. Format: IPV4 or IPV6 IP address.
  n2_bind_addr: # Optional TEXT. Sets local IP address to bind for N2 interface. Format: IPV4 or IPV6 IP address.
  n2_bind_interface: auto # Optional TEXT. Sets the network device to bind to for N2 interface.
  n3_bind_addr: # Optional TEXT. Sets local IP address to bind for N3 interface. Format: IPV4 or IPV6 IP address.
  n3_bind_interface: auto # Optional TEXT. Sets the network device to bind to for N3 interface.
  n3_ext_addr: # Optional TEXT. Sets the external IP address that is advertised to receive GTP-U packets from UPF via N3 interface. Format: IPV4 address.
  no_core: true # Optional BOOLEAN (false). Setting to true allows the gNB to run without a core. Supported: [false, true].

e2:
  enable_du_e2: false # Optional BOOLEAN (false). Enables the DU E2 agent. Supported: [false, true].
  addr: # Optional TEXT. Sets the RIC IP address.
  port: 36421 # Optional UINT (36421). Sets the RIC Port. Supported: [20000 - 40000].
  bind_addr: # Optional TEXT. Sets the local IP address to bind for RIC connection. Supported: IPv4 address.
  sctp_rto_initial: # Optional INT. Sets the initial retransmission timeout when creating the SCTP connection.
  sctp_rto_min: # Optional INT. Sets the minimum retransmission timeout for the SCTP connection.
  sctp_rto_max: # Optional INT. Sets the maximum retransmission timeout for the SCTP connection.
  sctp_initial_max_attempts: # Optional INT. Sets the maximum retransmission attempts for the initial SCTP connection.
  sctp_max_init_timeo: # Optional INT. Sets the maximum retransmission timeout for the initial SCTP connection.
  e2sm_kpm_enabled: false # Optional BOOLEAN (false). Enabled the E2SM KPM service module. Supported: [false, true].
  e2sm_rc_enabled: false # Optional BOOLEAN (false). Enabled the E2SM RC service module. Supported: [false, true].

ru_sdr:
  srate: 23.04 # Required FLOAT (61.44). Sets the sampling rate of the RF-frontend in MHz.
  device_driver: zmq # Required TEXT (uhd). RF device driver name. Supported: [uhd, zmq].
  device_args: tx_port=tcp://*:2000,rx_port=tcp://172.17.0.2:2001,id=srs_gnb,base_srate=23.04e6 # Optional TEXT. An argument that gets passed to the selected RF driver.
  tx_gain: 75 # Required FLOAT (50). Sets the transmit gain in dB. Supported: [0 - max value supported by radio].
  rx_gain: 75 # Required FLOAT (60). Sets the receive gain in dB. Supported: [0 - max value supported by radio].

cell_cfg:
  dl_arfcn: 368500 # Required UINT (536020). Sets the Downlink ARFCN.
  band: 3 # Optional TEXT (auto). Sets the NR band being used for the cell. If not specified, will be set automatically based on ARFCN. Supported: all release 17 bands.
  common_scs: 15 # Required UINT (15). Sets the subcarrier spacing in KHz to be used by the cell. Supported: [15, 30].
  channel_bandwidth_MHz: 20 # Required UINT (20). Sets the channel Bandwidth in MHz, the number of PRBs will be derived from this. Supported: [5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 90, 100].
  nof_antennas_dl: 1 # Optional UINT (1). Sets the number of antennas for downlink transmission. Supported: [1, 2, 4].
  nof_antennas_ul: 1 # Optional UINT (1). Sets the number of antennas for uplink transmission. Supported: [1, 2, 4].
  plmn: 72470 # Required TEXT (00101). Sets the Public Land Mobile Network code. Format: 7-digit PLMN code containing MCC & MNC.
  tac: 1 # Required UINT (7). Sets the Tracking Area Code.

  pdcch:
    common:
      coreset0_index: 12 # Optional INT. Sets the CORESET 0 index. Supported: [0 - 15].
      ss0_index: 0 # Optional UINT (0). Sets the SearchSpace#0 index. Supported: [0 - 15].
    dedicated:
      dci_format_0_1_and_1_1: false # Optional BOOLEAN (true). Sets whether to use non-fallback or fallback DCI format in UE SearchSpace#2. Supported: [false, true].
      ss2_type: ue_dedicated # Optional TEXT (ue_dedicated). Sets the SearchSpace type for UE dedicated SearchSpace#2. Supported: [common, ue_dedicated].

  prach:
    prach_config_index: 1 # Optional UINT. Sets the PRACH configuration index. If not set, the value is derived, so that the PRACH fits in an UL slot. Supported: [0 - 255].

log:
  # All gNB layers and components can be configured independently to output at various levels of detail. Logs can be configured to the following levels (from lowest to highest levels of detail):
  # none, error, warning, info, debug
  all_level: warning # Optional TEXT (warning). Sets a common log level across PHY, MAC, RLC, PDCP, RRC, SDAP, NGAP and GTPU layers.
  phy_level: warning # Optional TEXT (warning). Sets PHY log level.
  mac_level: warning # Optional TEXT (warning). Sets MAC log level.
  rlc_level: warning # Optional TEXT (warning). Sets RLC log level.
  pdcp_level: warning # Optional TEXT (warning). Sets PDCP log level.
  rrc_level: warning # Optional TEXT (warning). Sets RRC log level.
  sdap_level: warning # Optional TEXT (warning). Sets SDAP log level.
  ngap_level: warning # Optional TEXT (warning). Sets NGAP log level.
  gtpu_level: warning # Optional TEXT (warning). Sets GTPU log level.
  radio_level: info # Optional TEXT (info). Sets radio log level.
  fapi_level: warning # Optional TEXT (warning). Sets FAPI log level.
  ofh_level: warning # Optional TEXT (warning). Sets Open Fronthaul log level.
  f1ap_level: warning # Optional TEXT (warning). Sets F1AP log level.
  f1u_level: warning # Optional TEXT (warning). Sets F1u log level.
  du_level: warning # Optional TEXT (warning). Sets DU log level.
  cu_level: warning # Optional TEXT (warning). Sets CU log level.
  sec_level: warning # Optional TEXT (warning). Sets security functions level.
  lib_level: warning # Optional TEXT (warning). Sets generic log level.
  e2ap_level: warning # Optional TEXT (warning). Sets E2AP log level.
  config_level: none # Optional TEXT (none). Sets the config log level.
  metrics_level: none # Optional TEXT (none). Sets the metrics log level.
  hex_max_size: 0 # Optional UINT (0). Sets maximum number of bytes to print for hex messages. Supported: [0 - 1024]
  broadcast_enabled: false # Optional BOOLEAN (false). Enables logging in the PHY and MAC layer of broadcast messages and all PRACH opportunities. Supported: [false, true].
  phy_rx_symbols_filename: # Optional TEXT. Print received symbols to file. Symbols will be printed if a valid path is set. Format: file path. This file can be used in the srsRAN_matlab project.
  phy_rx_symbols_port: 0 # Optional TEXT. Set to a valid receive port number to dump the IQ symbols from that port only, or set to "all" to dump the IQ symbols from all UL receive ports. Only works if "phy_rx_symbols_filename" is set. Supported: [NON-NEGATIVE or all].
  phy_rx_symbols_prach: false # Optional BOOLEAN (false). Set to true to dump the IQ symbols from all the PRACH ports. Only works if "phy_rx_symbols_filename" is set. Supported: [false, true].
  tracing_filename: # Optional TEXT. Set to a valid file name to enable tracing log.
  f1ap_json_enabled: false # Optional BOOLEAN (false). Enables the JSON logging of F1AP PDUs. Supported: [false, true].

pcap:
  ngap_filename: /tmp/gnb_ngap.pcap # Optional TEXT (/tmp/gnb_ngap.pcap). Path for NGAP PCAPs.
  ngap_enable: false # Optional BOOLEAN (false). Enable/disable NGAP packet capture. Supported: [false, true].
  n3_filename: /tmp/gnb_n3.pcap # Optional TEXT (/tmp/gnb_n3.pcap). Path for N3 PCAPs.
  n3_enable: false # Optional BOOLEAN (false). Enable/disable N3 packet capture. Supported: [false, true].
  e1ap_filename: /tmp/gnb_e1ap.pcap # Optional TEXT (/tmp/gnb_e1ap.pcap). Path for E1AP PCAPs.
  e1ap_enable: false # Optional BOOLEAN (false). Enable/disable E1AP packet capture. Supported: [false, true].
  f1ap_filename: /tmp/gnb_f1ap.pcap # Optional TEXT (/tmp/gnb_f1ap.pcap). Path for F1AP PCAPs.
  f1ap_enable: false # Optional BOOLEAN (false). Enable/disable F1AP packet capture. Supported: [false, true].
  f1u_filename: /tmp/gnb_f1u.pcap # Optional TEXT (/tmp/gnb_f1ap.pcap). Path for F1AP PCAPs.
  f1u_enable: false # Optional BOOLEAN (false). Enable/disable F1AP packet capture. Supported: [false, true].
  rlc_filename: /tmp/gnb_rlc.pcap # Optional TEXT (tmp/gnb_rlc.pcap). Path for RLC PCAPs.
  rlc_rb_type: all # Optional TEXT. Sets the RLC PCAP RB type. Supported: [all, srb, drb].
  rlc_enable: false # Optional BOOLEAN (false). Enable/disable RLC packet capture. Supported: [false, true].
  mac_filename: /tmp/gnb_mac.pcap # Optional TEXT (/tmp/gnb_mac.pcap). Path for MAC PCAPs.
  mac_type: udp # Optional TEXT (udp). Sets the MAC PCAP pcap type. Supported: [DLT or UDP].
  mac_enable: false # Optional BOOLEAN (false). Enable/disable MAC packet capture. Supported: [false, true].
  e2ap_filename: /tmp/gnb_e2ap.pcap # Optional TEXT (/tmp/gnb_e2ap.pcap). Path for E2AP PCAPs.
  e2ap_enable: true # Optional BOOLEAN (false). Enable/disable E2AP packet capture. Supported: [false, true].

metrics:
  rlc_report_period: 1000 # Optional UINT (1000). Sets the RLC metrics report period in milliseconds. Supported [0 - inf]
  rlc_json_enable: true # Enable RLC metrics reporting (need to deliver measurements to E2SM_KPM service model)
  pdcp_report_period: 0 # Optional UINT (0). Sets the PDCP metrics report period.
  cu_cp_statistics_report_period: 1 # Optional UINT (1). Sets the CU-CP statistics report period in seconds. Set this value to 0 to disable this feature. Supported: [0 - inf].
  cu_up_statistics_report_period: 1 # Optional UINT (1). Sets the CU-UP statistics report period in seconds. Set this value to 0 to disable this feature. Supported: [0 - inf].
  enable_json_metrics: false # Optional BOOLEAN (false). Enables JSON metrics reporting. Supported: [false, true].
  addr: 127.0.0.1 # Optional TEXT:IPV4 (127.0.0.1). Sets the metrics address. Supported: IPV4 address.
  port: 55555 # Optional UINT. Sets the metrics UPD port. Supported: [0 - 65535].
  autostart_stdout_metrics: true # Optional BOOLEAN (false). Sets whether or note to autostart stdout metrics reporting. Supported [false, true].
  stdout_metrics_period: # Optional UINT (1). Sets the DU statistics report period in milliseconds. This metrics sets the console output period. Supported: [0 - inf].